# Generated by Django 3.1.1 on 2022-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
